import type { Job, University, Property, Destination, Opportunity, DashboardStats } from "@/types";

export const COUNTRIES = [
  { code: "DE", name: "Germany", flag: "🇩🇪" },
  { code: "FR", name: "France", flag: "🇫🇷" },
  { code: "NL", name: "Netherlands", flag: "🇳🇱" },
  { code: "SE", name: "Sweden", flag: "🇸🇪" },
  { code: "NO", name: "Norway", flag: "🇳🇴" },
  { code: "CH", name: "Switzerland", flag: "🇨🇭" },
  { code: "AT", name: "Austria", flag: "🇦🇹" },
  { code: "BE", name: "Belgium", flag: "🇧🇪" },
  { code: "DK", name: "Denmark", flag: "🇩🇰" },
  { code: "FI", name: "Finland", flag: "🇫🇮" },
  { code: "PL", name: "Poland", flag: "🇵🇱" },
  { code: "CZ", name: "Czech Republic", flag: "🇨🇿" },
  { code: "ES", name: "Spain", flag: "🇪🇸" },
  { code: "IT", name: "Italy", flag: "🇮🇹" },
  { code: "PT", name: "Portugal", flag: "🇵🇹" },
];

export const JOB_CATEGORIES = [
  "Technology", "Finance", "Healthcare", "Engineering", "Marketing",
  "Design", "Operations", "Legal", "Education", "Research", "Sales", "HR"
];

export const JOBS: Job[] = [
  {
    id: "j1",
    title: "Senior Software Engineer",
    company: "SAP SE",
    companyLogo: "https://picsum.photos/seed/sap/80/80",
    location: "Berlin, Germany",
    country: "Germany",
    countryFlag: "🇩🇪",
    salary: "₹72,00,000 – ₹95,00,000/yr",
    salaryMin: 7200000,
    salaryMax: 9500000,
    type: "Full-time",
    category: "Technology",
    description: "Join SAP's core engineering team building next-generation ERP solutions. Work with cutting-edge cloud technologies in the heart of Berlin.",
    requirements: ["5+ years backend development", "Java or Go expertise", "Microservices architecture", "Cloud (AWS/GCP/Azure)"],
    benefits: ["Relocation assistance", "Health insurance", "Stock options", "30 days PTO", "Remote flexibility"],
    posted: "2 days ago",
    deadline: "2026-10-15",
    applicants: 234,
    verified: true,
    featured: true,
    remote: true,
    visa: true,
    experience: "Senior (5+ years)",
    skills: ["Java", "Kubernetes", "Spring Boot", "PostgreSQL"],
  },
  {
    id: "j2",
    title: "Data Scientist — Climate Analytics",
    company: "Siemens Energy",
    companyLogo: "https://picsum.photos/seed/siemens/80/80",
    location: "Munich, Germany",
    country: "Germany",
    countryFlag: "🇩🇪",
    salary: "₹62,00,000 – ₹82,00,000/yr",
    salaryMin: 6200000,
    salaryMax: 8200000,
    type: "Full-time",
    category: "Technology",
    description: "Drive climate impact through data science. Build ML models predicting energy transitions across Europe's power grid.",
    requirements: ["Python, R expertise", "ML frameworks (TensorFlow/PyTorch)", "3+ years data science", "Energy sector preferred"],
    benefits: ["Visa sponsorship", "Housing allowance", "German language courses", "Gym membership"],
    posted: "5 days ago",
    deadline: "2026-10-30",
    applicants: 178,
    verified: true,
    featured: true,
    remote: false,
    visa: true,
    experience: "Mid-level (3–5 years)",
    skills: ["Python", "TensorFlow", "SQL", "Tableau"],
  },
  {
    id: "j3",
    title: "Product Manager — FinTech",
    company: "N26 Bank",
    companyLogo: "https://picsum.photos/seed/n26/80/80",
    location: "Berlin, Germany",
    country: "Germany",
    countryFlag: "🇩🇪",
    salary: "₹78,00,000 – ₹1,05,00,000/yr",
    salaryMin: 7800000,
    salaryMax: 10500000,
    type: "Full-time",
    category: "Finance",
    description: "Own the product roadmap for N26's next growth phase. Lead cross-functional teams to ship banking products loved by 8M+ customers.",
    requirements: ["4+ years product management", "Fintech background preferred", "Data-driven mindset", "Agile expertise"],
    benefits: ["Equity", "Travel budget", "Unlimited PTO", "Mental health support"],
    posted: "1 week ago",
    deadline: "2026-11-05",
    applicants: 412,
    verified: true,
    featured: false,
    remote: true,
    visa: true,
    experience: "Senior (5+ years)",
    skills: ["Product Strategy", "SQL", "Figma", "OKRs"],
  },
  {
    id: "j4",
    title: "UX/UI Designer — Mobile",
    company: "Booking.com",
    companyLogo: "https://picsum.photos/seed/booking/80/80",
    location: "Amsterdam, Netherlands",
    country: "Netherlands",
    countryFlag: "🇳🇱",
    salary: "₹55,00,000 – ₹72,00,000/yr",
    salaryMin: 5500000,
    salaryMax: 7200000,
    type: "Full-time",
    category: "Design",
    description: "Design intuitive mobile experiences for 28M+ daily travelers. Work in Amsterdam's tech hub on world-class design challenges.",
    requirements: ["4+ years UX/UI design", "Figma mastery", "Mobile-first design", "User research experience"],
    benefits: ["Relocation package", "Travel credits", "Learning budget", "MacBook Pro"],
    posted: "3 days ago",
    deadline: "2026-10-20",
    applicants: 356,
    verified: true,
    featured: true,
    remote: false,
    visa: true,
    experience: "Mid-level (3–5 years)",
    skills: ["Figma", "Prototyping", "Design Systems", "A/B Testing"],
  },
  {
    id: "j5",
    title: "Investment Analyst",
    company: "ABN AMRO",
    companyLogo: "https://picsum.photos/seed/abnamro/80/80",
    location: "Amsterdam, Netherlands",
    country: "Netherlands",
    countryFlag: "🇳🇱",
    salary: "₹52,00,000 – ₹70,00,000/yr",
    salaryMin: 5200000,
    salaryMax: 7000000,
    type: "Full-time",
    category: "Finance",
    description: "Join ABN AMRO's sustainable investment division. Analyze European market trends and develop ESG-focused investment strategies.",
    requirements: ["CFA Level 1 preferred", "2+ years finance", "Excel & Bloomberg", "Dutch or English"],
    benefits: ["Pension scheme", "Annual bonus", "Health insurance", "Work from home 3 days"],
    posted: "4 days ago",
    deadline: "2026-11-01",
    applicants: 289,
    verified: true,
    featured: false,
    remote: false,
    visa: false,
    experience: "Junior (1–2 years)",
    skills: ["Excel", "Bloomberg", "Financial Modeling", "ESG"],
  },
  {
    id: "j6",
    title: "DevOps Engineer",
    company: "Spotify",
    companyLogo: "https://picsum.photos/seed/spotify/80/80",
    location: "Stockholm, Sweden",
    country: "Sweden",
    countryFlag: "🇸🇪",
    salary: "₹68,00,000 – ₹90,00,000/yr",
    salaryMin: 6800000,
    salaryMax: 9000000,
    type: "Full-time",
    category: "Technology",
    description: "Scale Spotify's infrastructure to serve 600M+ users. Work on cutting-edge DevOps challenges in Stockholm's vibrant tech scene.",
    requirements: ["Kubernetes & Docker expert", "CI/CD pipelines", "GCP/AWS", "4+ years DevOps"],
    benefits: ["Spotify Premium", "Relocation support", "6 months parental leave", "Stock units"],
    posted: "6 days ago",
    deadline: "2026-10-25",
    applicants: 521,
    verified: true,
    featured: false,
    remote: true,
    visa: true,
    experience: "Senior (5+ years)",
    skills: ["Kubernetes", "Terraform", "GCP", "Jenkins"],
  },
  {
    id: "j7",
    title: "Healthcare Data Analyst",
    company: "Roche",
    companyLogo: "https://picsum.photos/seed/roche/80/80",
    location: "Basel, Switzerland",
    country: "Switzerland",
    countryFlag: "🇨🇭",
    salary: "₹90,00,000 – ₹1,20,00,000/yr",
    salaryMin: 9000000,
    salaryMax: 12000000,
    type: "Full-time",
    category: "Healthcare",
    description: "Leverage global clinical data to improve patient outcomes. Join Roche's data team in beautiful Basel with world-class healthcare research.",
    requirements: ["Biostatistics or data science degree", "R/SAS expertise", "Clinical trial data experience", "3+ years pharma"],
    benefits: ["High salary", "Premium health coverage", "Paid research trips", "Childcare support"],
    posted: "1 week ago",
    deadline: "2026-11-15",
    applicants: 198,
    verified: true,
    featured: true,
    remote: false,
    visa: true,
    experience: "Mid-level (3–5 years)",
    skills: ["R", "SAS", "Clinical Data", "Biostatistics"],
  },
  {
    id: "j8",
    title: "Marketing Manager — EMEA",
    company: "LVMH",
    companyLogo: "https://picsum.photos/seed/lvmh/80/80",
    location: "Paris, France",
    country: "France",
    countryFlag: "🇫🇷",
    salary: "₹65,00,000 – ₹85,00,000/yr",
    salaryMin: 6500000,
    salaryMax: 8500000,
    type: "Full-time",
    category: "Marketing",
    description: "Shape the EMEA marketing strategy for world's leading luxury group. Based in iconic Paris, working across 75+ prestigious brands.",
    requirements: ["6+ years luxury marketing", "French preferred", "Digital & traditional marketing", "Brand management"],
    benefits: ["Employee discounts", "Fashion week access", "Luxury perks", "Excellent salary"],
    posted: "2 weeks ago",
    deadline: "2026-10-31",
    applicants: 634,
    verified: true,
    featured: false,
    remote: false,
    visa: false,
    experience: "Senior (5+ years)",
    skills: ["Brand Strategy", "Digital Marketing", "French", "Campaign Management"],
  },
];

export const UNIVERSITIES: University[] = [
  {
    id: "u1",
    name: "Technical University of Munich",
    country: "Germany",
    countryFlag: "🇩🇪",
    city: "Munich",
    image: "https://picsum.photos/seed/tum/800/400",
    rank: 38,
    rankLabel: "#38 World, #1 Germany",
    programs: ["Computer Science", "Engineering", "MBA", "Data Science", "Robotics", "AI"],
    tuitionMin: 300000,
    tuitionMax: 2500000,
    tuitionLabel: "₹3,00,000 – ₹25,00,000/yr",
    type: "Public",
    intake: ["Winter (Oct)", "Summer (Apr)"],
    language: ["English", "German"],
    acceptance: 8,
    scholarships: true,
    verified: true,
    featured: true,
    description: "Germany's top technical university, consistently ranked among Europe's best. Known for engineering excellence and strong industry ties.",
    founded: 1868,
    students: 50000,
    rating: 4.8,
  },
  {
    id: "u2",
    name: "University of Amsterdam",
    country: "Netherlands",
    countryFlag: "🇳🇱",
    city: "Amsterdam",
    image: "https://picsum.photos/seed/uva/800/400",
    rank: 55,
    rankLabel: "#55 World, #1 Netherlands",
    programs: ["Business", "Law", "Medicine", "Social Sciences", "Arts", "Economics"],
    tuitionMin: 850000,
    tuitionMax: 2200000,
    tuitionLabel: "₹8,50,000 – ₹22,00,000/yr",
    type: "Public",
    intake: ["September"],
    language: ["English", "Dutch"],
    acceptance: 35,
    scholarships: true,
    verified: true,
    featured: true,
    description: "One of Europe's most prestigious research universities, located in the vibrant heart of Amsterdam with world-class faculty.",
    founded: 1632,
    students: 36000,
    rating: 4.6,
  },
  {
    id: "u3",
    name: "ETH Zurich",
    country: "Switzerland",
    countryFlag: "🇨🇭",
    city: "Zurich",
    image: "https://picsum.photos/seed/eth/800/400",
    rank: 7,
    rankLabel: "#7 World, #1 Switzerland",
    programs: ["Engineering", "Science", "Math", "Computer Science", "Architecture", "Quantum Computing"],
    tuitionMin: 120000,
    tuitionMax: 150000,
    tuitionLabel: "₹1,20,000 – ₹1,50,000/yr",
    type: "Public",
    intake: ["September"],
    language: ["English", "German"],
    acceptance: 27,
    scholarships: true,
    verified: true,
    featured: true,
    description: "World's leading science and technology university. Home to 21 Nobel laureates, located in beautiful Zurich.",
    founded: 1855,
    students: 21000,
    rating: 4.9,
  },
  {
    id: "u4",
    name: "Sciences Po Paris",
    country: "France",
    countryFlag: "🇫🇷",
    city: "Paris",
    image: "https://picsum.photos/seed/sciencespo/800/400",
    rank: 267,
    rankLabel: "#267 World, Top 5 France",
    programs: ["Political Science", "International Relations", "Law", "Sociology", "Economics", "Journalism"],
    tuitionMin: 1400000,
    tuitionMax: 2900000,
    tuitionLabel: "₹14,00,000 – ₹29,00,000/yr",
    type: "Public",
    intake: ["September"],
    language: ["English", "French"],
    acceptance: 12,
    scholarships: true,
    verified: true,
    featured: false,
    description: "France's most prestigious social sciences school, producing European leaders, presidents, and CEOs since 1872.",
    founded: 1872,
    students: 14000,
    rating: 4.7,
  },
  {
    id: "u5",
    name: "KTH Royal Institute of Technology",
    country: "Sweden",
    countryFlag: "🇸🇪",
    city: "Stockholm",
    image: "https://picsum.photos/seed/kth/800/400",
    rank: 89,
    rankLabel: "#89 World, #1 Sweden",
    programs: ["Engineering", "Technology", "Architecture", "Industrial Economics", "ICT"],
    tuitionMin: 1100000,
    tuitionMax: 1800000,
    tuitionLabel: "₹11,00,000 – ₹18,00,000/yr",
    type: "Public",
    intake: ["September"],
    language: ["English", "Swedish"],
    acceptance: 30,
    scholarships: true,
    verified: true,
    featured: false,
    description: "Sweden's largest technical university, at the forefront of innovation in clean technology, mobility, and digitalization.",
    founded: 1827,
    students: 18000,
    rating: 4.5,
  },
  {
    id: "u6",
    name: "Warsaw University of Technology",
    country: "Poland",
    countryFlag: "🇵🇱",
    city: "Warsaw",
    image: "https://picsum.photos/seed/wat/800/400",
    rank: 601,
    rankLabel: "#601 World, #1 Poland",
    programs: ["Computer Science", "Civil Engineering", "Electronics", "Mechanical Engineering"],
    tuitionMin: 200000,
    tuitionMax: 600000,
    tuitionLabel: "₹2,00,000 – ₹6,00,000/yr",
    type: "Public",
    intake: ["October", "February"],
    language: ["English", "Polish"],
    acceptance: 45,
    scholarships: true,
    verified: true,
    featured: false,
    description: "Poland's premier technical university offering high-quality STEM education at very affordable tuition rates.",
    founded: 1915,
    students: 27000,
    rating: 4.2,
  },
];

export const PROPERTIES: Property[] = [
  {
    id: "p1",
    title: "Modern Studio in Prenzlauer Berg",
    type: "Studio",
    country: "Germany",
    countryFlag: "🇩🇪",
    city: "Berlin",
    image: "https://picsum.photos/seed/berlin-apt/800/500",
    images: ["https://picsum.photos/seed/berlin-apt1/800/500", "https://picsum.photos/seed/berlin-apt2/800/500"],
    rentMin: 85000,
    rentMax: 95000,
    rentLabel: "₹85,000/month",
    bedrooms: 0,
    bathrooms: 1,
    area: 35,
    furnished: true,
    utilities: true,
    petFriendly: false,
    verified: true,
    featured: true,
    nearUniversity: true,
    available: "Immediately",
    description: "Beautifully renovated studio in Berlin's hippest neighborhood. Full kitchen, fast WiFi, and walking distance to U-Bahn.",
    amenities: ["WiFi", "Washing Machine", "Dishwasher", "Bike Storage", "Balcony"],
    rating: 4.8,
    reviews: 24,
  },
  {
    id: "p2",
    title: "Spacious 2-Bed in Le Marais",
    type: "Apartment",
    country: "France",
    countryFlag: "🇫🇷",
    city: "Paris",
    image: "https://picsum.photos/seed/paris-apt/800/500",
    images: [],
    rentMin: 160000,
    rentMax: 180000,
    rentLabel: "₹1,60,000/month",
    bedrooms: 2,
    bathrooms: 1,
    area: 65,
    furnished: true,
    utilities: false,
    petFriendly: true,
    verified: true,
    featured: true,
    nearUniversity: false,
    available: "Oct 15",
    description: "Stunning Haussmann-style apartment in Le Marais. High ceilings, original parquet floors, minutes from the Pompidou.",
    amenities: ["WiFi", "Heating", "Elevator", "Intercom", "Storage"],
    rating: 4.9,
    reviews: 41,
  },
  {
    id: "p3",
    title: "Cozy Room in Student House",
    type: "Shared",
    country: "Netherlands",
    countryFlag: "🇳🇱",
    city: "Amsterdam",
    image: "https://picsum.photos/seed/amsterdam-room/800/500",
    images: [],
    rentMin: 70000,
    rentMax: 80000,
    rentLabel: "₹70,000/month",
    bedrooms: 1,
    bathrooms: 1,
    area: 18,
    furnished: true,
    utilities: true,
    petFriendly: false,
    verified: true,
    featured: false,
    nearUniversity: true,
    available: "Nov 1",
    description: "Furnished room in a friendly 5-person student house near UvA. Bills included, great housemates, bike storage.",
    amenities: ["WiFi", "All Bills", "Washing Machine", "Garden", "Bike Storage"],
    rating: 4.5,
    reviews: 18,
  },
  {
    id: "p4",
    title: "1-Bed near Chalmers University",
    type: "Apartment",
    country: "Sweden",
    countryFlag: "🇸🇪",
    city: "Gothenburg",
    image: "https://picsum.photos/seed/gothenburg-apt/800/500",
    images: [],
    rentMin: 65000,
    rentMax: 72000,
    rentLabel: "₹65,000/month",
    bedrooms: 1,
    bathrooms: 1,
    area: 42,
    furnished: false,
    utilities: false,
    petFriendly: true,
    verified: true,
    featured: false,
    nearUniversity: true,
    available: "Immediately",
    description: "Bright Scandinavian apartment 10 mins walk from Chalmers. Modern kitchen, great natural light, quiet neighborhood.",
    amenities: ["Parking", "Gym", "Sauna", "Elevator", "Laundry Room"],
    rating: 4.4,
    reviews: 12,
  },
  {
    id: "p5",
    title: "Luxury Penthouse with Alp Views",
    type: "Apartment",
    country: "Switzerland",
    countryFlag: "🇨🇭",
    city: "Zurich",
    image: "https://picsum.photos/seed/zurich-penthouse/800/500",
    images: [],
    rentMin: 380000,
    rentMax: 420000,
    rentLabel: "₹3,80,000/month",
    bedrooms: 3,
    bathrooms: 2,
    area: 120,
    furnished: true,
    utilities: true,
    petFriendly: false,
    verified: true,
    featured: true,
    nearUniversity: false,
    available: "Dec 1",
    description: "Exceptional penthouse with panoramic Alpine and lake views. Concierge service, underground parking, private terrace.",
    amenities: ["Concierge", "Underground Parking", "Terrace", "Lake View", "Smart Home"],
    rating: 5.0,
    reviews: 7,
  },
  {
    id: "p6",
    title: "Affordable Studio in Krakow Old Town",
    type: "Studio",
    country: "Poland",
    countryFlag: "🇵🇱",
    city: "Krakow",
    image: "https://picsum.photos/seed/krakow-studio/800/500",
    images: [],
    rentMin: 28000,
    rentMax: 35000,
    rentLabel: "₹28,000/month",
    bedrooms: 0,
    bathrooms: 1,
    area: 28,
    furnished: true,
    utilities: true,
    petFriendly: false,
    verified: true,
    featured: false,
    nearUniversity: true,
    available: "Immediately",
    description: "Charming studio steps from Krakow's UNESCO Old Town. Perfect for students or digital nomads — great value.",
    amenities: ["WiFi", "All Bills Included", "Security Code Entry", "Nearby Tram"],
    rating: 4.3,
    reviews: 29,
  },
];

export const DESTINATIONS: Destination[] = [
  {
    id: "d1",
    name: "Berlin",
    country: "Germany",
    countryFlag: "🇩🇪",
    tagline: "Europe's startup capital meets world-class culture",
    image: "https://picsum.photos/seed/berlin-city/900/500",
    category: ["Tech Hub", "Culture", "Nightlife", "Affordable"],
    costOfLiving: "Medium",
    costIndex: 72,
    safetyScore: 82,
    qualityOfLife: 88,
    climate: "Temperate",
    language: ["German", "English widely spoken"],
    population: "3.8 million",
    visaFriendly: true,
    workOpportunities: "Excellent",
    description: "Berlin is the beating heart of European tech, arts, and diversity. Home to 300+ startups, world-class museums, and a legendary nightlife scene.",
    highlights: ["Start-up ecosystem", "Affordable rent", "Excellent public transport", "Rich history", "International community"],
    monthlyBudget: 120000,
    featured: true,
  },
  {
    id: "d2",
    name: "Amsterdam",
    country: "Netherlands",
    countryFlag: "🇳🇱",
    tagline: "Where canals meet cutting-edge innovation",
    image: "https://picsum.photos/seed/amsterdam-city/900/500",
    category: ["Finance", "Tech", "Culture", "Cycling"],
    costOfLiving: "High",
    costIndex: 88,
    safetyScore: 88,
    qualityOfLife: 91,
    climate: "Maritime",
    language: ["Dutch", "English (99% fluency)"],
    population: "900,000",
    visaFriendly: true,
    workOpportunities: "Excellent",
    description: "Amsterdam is Europe's most international city — a global tech and finance hub where English is the de facto business language.",
    highlights: ["Best English speakers", "ASML, Booking.com, Uber EU HQ", "Canal lifestyle", "Safe cycling city", "Schiphol hub"],
    monthlyBudget: 165000,
    featured: true,
  },
  {
    id: "d3",
    name: "Lisbon",
    country: "Portugal",
    countryFlag: "🇵🇹",
    tagline: "Sun, affordable living, and Europe's fastest-growing tech scene",
    image: "https://picsum.photos/seed/lisbon-city/900/500",
    category: ["Digital Nomad", "Affordable", "Beach", "Tech"],
    costOfLiving: "Medium",
    costIndex: 65,
    safetyScore: 90,
    qualityOfLife: 85,
    climate: "Mediterranean",
    language: ["Portuguese", "English well spoken"],
    population: "550,000",
    visaFriendly: true,
    workOpportunities: "Good",
    description: "Lisbon has exploded onto the global stage as a digital nomad paradise and serious tech hub, with sunshine 300 days a year.",
    highlights: ["NHR tax regime", "Web Summit location", "Golden Visa", "Atlantic beaches", "Low crime"],
    monthlyBudget: 95000,
    featured: true,
  },
  {
    id: "d4",
    name: "Stockholm",
    country: "Sweden",
    countryFlag: "🇸🇪",
    tagline: "Innovation, Nordic lifestyle, and incredible work-life balance",
    image: "https://picsum.photos/seed/stockholm-city/900/500",
    category: ["Tech", "Sustainability", "High Income", "Nature"],
    costOfLiving: "Very High",
    costIndex: 95,
    safetyScore: 85,
    qualityOfLife: 95,
    climate: "Nordic",
    language: ["Swedish", "English universally spoken"],
    population: "975,000",
    visaFriendly: true,
    workOpportunities: "Excellent",
    description: "Stockholm is the home of Spotify, Klarna, and Minecraft — Europe's startup unicorn factory with world-leading quality of life.",
    highlights: ["Spotify, Klarna, IKEA HQ", "Top work-life balance", "Universal healthcare", "Nature access", "Safe & clean"],
    monthlyBudget: 185000,
    featured: false,
  },
  {
    id: "d5",
    name: "Vienna",
    country: "Austria",
    countryFlag: "🇦🇹",
    tagline: "Most liveable city on Earth, 15 years running",
    image: "https://picsum.photos/seed/vienna-city/900/500",
    category: ["Culture", "Quality of Life", "History", "Music"],
    costOfLiving: "High",
    costIndex: 84,
    safetyScore: 94,
    qualityOfLife: 99,
    climate: "Continental",
    language: ["German", "English widely spoken"],
    population: "1.9 million",
    visaFriendly: true,
    workOpportunities: "Good",
    description: "Vienna tops every quality-of-life index for a reason: a city of imperial grandeur, unmatched culture, and superb public services.",
    highlights: ["#1 Most Liveable City", "Imperial architecture", "World-class coffee culture", "UN headquarters", "Excellent safety"],
    monthlyBudget: 145000,
    featured: false,
  },
  {
    id: "d6",
    name: "Warsaw",
    country: "Poland",
    countryFlag: "🇵🇱",
    tagline: "Central Europe's fastest-growing economy and tech powerhouse",
    image: "https://picsum.photos/seed/warsaw-city/900/500",
    category: ["Affordable", "Tech", "Business", "Growing"],
    costOfLiving: "Low",
    costIndex: 48,
    safetyScore: 78,
    qualityOfLife: 78,
    climate: "Continental",
    language: ["Polish", "English in business"],
    population: "1.8 million",
    visaFriendly: true,
    workOpportunities: "Excellent",
    description: "Warsaw is Central Europe's economic powerhouse — affordable, ambitious, and home to the fastest-growing tech ecosystem in the EU.",
    highlights: ["Very affordable cost of living", "Booming startup scene", "EU member", "Young dynamic population", "Great nightlife"],
    monthlyBudget: 65000,
    featured: false,
  },
];

export const OPPORTUNITIES: Opportunity[] = [
  {
    id: "o1",
    title: "Erasmus+ Masters Scholarship",
    organization: "European Commission",
    country: "EU-Wide",
    countryFlag: "🇪🇺",
    type: "Scholarship",
    amount: 2100000,
    amountLabel: "Up to ₹21,00,000/yr",
    deadline: "2026-12-01",
    eligibility: ["Non-EU students", "Bachelors degree", "English proficiency"],
    description: "Full scholarship covering tuition, living expenses, and travel for master's programs at top European universities.",
    featured: true,
    verified: true,
    category: "Education",
    link: "#",
  },
  {
    id: "o2",
    title: "DAAD Research Grant — Germany",
    organization: "DAAD Germany",
    country: "Germany",
    countryFlag: "🇩🇪",
    type: "Grant",
    amount: 1400000,
    amountLabel: "₹14,00,000 + flights",
    deadline: "2026-11-15",
    eligibility: ["PhD/Postdoc researchers", "STEM fields", "Strong academic record"],
    description: "Germany's premier research grant for international scholars, funding residencies at leading German universities and institutes.",
    featured: true,
    verified: true,
    category: "Research",
    link: "#",
  },
  {
    id: "o3",
    title: "Amsterdam Tech Talent Visa",
    organization: "IND Netherlands",
    country: "Netherlands",
    countryFlag: "🇳🇱",
    type: "Fellowship",
    amount: 0,
    amountLabel: "Fast-track Visa",
    deadline: "2026-12-31",
    eligibility: ["Tech professionals", "Job offer required", "Salary > ₹52,00,000/yr"],
    description: "Streamlined Netherlands residence permit for skilled tech workers with an employer sponsor. Process time: 2 weeks.",
    featured: true,
    verified: true,
    category: "Visa",
    link: "#",
  },
  {
    id: "o4",
    title: "Sweden Work Abroad Programme",
    organization: "Swedish Institute",
    country: "Sweden",
    countryFlag: "🇸🇪",
    type: "Exchange",
    amount: 900000,
    amountLabel: "₹9,00,000 stipend",
    deadline: "2026-10-31",
    eligibility: ["Professionals 25–40", "Leadership potential", "English fluency"],
    description: "3-month fully funded professional exchange in Sweden, working with Swedish companies and civil society organizations.",
    featured: false,
    verified: true,
    category: "Professional",
    link: "#",
  },
  {
    id: "o5",
    title: "EIT Digital Summer School",
    organization: "EIT Digital",
    country: "EU-Wide",
    countryFlag: "🇪🇺",
    type: "Training",
    amount: 350000,
    amountLabel: "₹3,50,000 coverage",
    deadline: "2027-01-15",
    eligibility: ["Engineering students", "Innovation interest", "Team player"],
    description: "Europe's premier tech innovation training. 8 weeks across 3 EU cities, working on real startup challenges with leading mentors.",
    featured: false,
    verified: true,
    category: "Training",
    link: "#",
  },
  {
    id: "o6",
    title: "Portugal Golden Visa Programme",
    organization: "Government of Portugal",
    country: "Portugal",
    countryFlag: "🇵🇹",
    type: "Fellowship",
    amount: 0,
    amountLabel: "Residency Permit",
    deadline: "2026-12-31",
    eligibility: ["Investment ₹2.5Cr+", "Clean criminal record", "Qualifying investment"],
    description: "Portugal's residency-by-investment programme granting EU residence, travel freedom, and path to citizenship in 5 years.",
    featured: false,
    verified: true,
    category: "Residency",
    link: "#",
  },
];

export const DASHBOARD_STATS: DashboardStats = {
  profileViews: 847,
  applicationsCount: 12,
  savedItems: 38,
  interviews: 3,
  activityTimeline: [
    { id: "a1", action: "Application submitted", details: "Senior Software Engineer at SAP SE", time: "2 hours ago", type: "application" },
    { id: "a2", action: "Job saved", details: "UX/UI Designer at Booking.com", time: "5 hours ago", type: "save" },
    { id: "a3", action: "Profile viewed", details: "HR Manager from N26 viewed your profile", time: "Yesterday", type: "view" },
    { id: "a4", action: "Interview scheduled", details: "Video call with Siemens Energy — Oct 18", time: "Yesterday", type: "message" },
    { id: "a5", action: "New match found", details: "3 new jobs matching your profile", time: "2 days ago", type: "match" },
    { id: "a6", action: "University saved", details: "ETH Zurich — Masters in Computer Science", time: "3 days ago", type: "save" },
    { id: "a7", action: "Application viewed", details: "Booking.com opened your application", time: "4 days ago", type: "view" },
  ],
  applicationsByStatus: [
    { name: "Applied", value: 5, color: "#2563EB" },
    { name: "In Review", value: 3, color: "#D4A72C" },
    { name: "Interview", value: 2, color: "#16A34A" },
    { name: "Rejected", value: 2, color: "#EF4444" },
  ],
  jobsByCategory: [
    { name: "Technology", jobs: 1420, applications: 4 },
    { name: "Finance", jobs: 890, applications: 3 },
    { name: "Design", jobs: 560, applications: 2 },
    { name: "Marketing", jobs: 740, applications: 2 },
    { name: "Healthcare", jobs: 380, applications: 1 },
  ],
};

export const STATS_NUMBERS = {
  jobs: "12,400+",
  universities: "850+",
  properties: "28,000+",
  destinations: 47,
  users: "2.1M+",
  countries: 27,
};

export const TESTIMONIALS = [
  {
    id: "t1",
    name: "Priya Sharma",
    role: "Software Engineer at SAP",
    location: "Berlin, Germany",
    image: "https://picsum.photos/seed/priya/80/80",
    text: "Europium helped me find my dream job in Berlin in just 3 weeks. The visa guidance and company verification gave me complete confidence.",
    rating: 5,
  },
  {
    id: "t2",
    name: "Arjun Mehta",
    role: "Masters Student at TU Munich",
    location: "Munich, Germany",
    image: "https://picsum.photos/seed/arjun/80/80",
    text: "I got into TU Munich through the scholarship listings on Europium. The application guidance was invaluable. Best platform for Europe-bound students.",
    rating: 5,
  },
  {
    id: "t3",
    name: "Sneha Reddy",
    role: "UX Designer at Booking.com",
    location: "Amsterdam, Netherlands",
    image: "https://picsum.photos/seed/sneha/80/80",
    text: "From job search to finding my apartment in Amsterdam — Europium covered everything. Saved months of research.",
    rating: 5,
  },
];
